### ISSUE TITLE
Unable to view Users

### ISSUE THREAD

**Issue by hermanschutte** [ForestAdmin/forest-laravel#18] opened 2016-11-21 08:48 UTC
Get the following error when trying to view users:

```Call to undefined method Illuminate\Database\Query\Builder::oauthidentity()```

**Comment by hermanschutte** [comment] 2016-11-29 08:00
Any update on this? As well as the other items like time-based charts and actions? It's quite important for us that these features are added ASAP so we can start using the product fully.

**Comment by arnaudbesnier** [comment] 2016-12-02 01:00
I am starting to investigate this issue.

**Comment by arnaudbesnier** [comment] 2016-12-02 02:32
@hermanschutte the package finds `oauthidentity` for your users model class name. Is it the real name of the class in your model declaration?

**Comment by arnaudbesnier** [comment] 2016-12-02 03:32
@hermanschutte I think I reproduced your issue. The fix is in this pull request: https://github.com/ForestAdmin/forest-laravel/pull/19

I'll release the new fixed version today.

**Comment by hermanschutte** [comment] 2016-12-04 18:13
Doesn't seem to be working yet unfortunately. No error anymore, but the query never returns any results and eventually seems to time out. This also causes the Total Users chart to fail.

Please re-open this.

**Comment by arnaudbesnier** [comment] 2016-12-05 05:58
Hi @hermanschutte,
sorry to hear that...

The requests to retrieve records (users in your case here) have pagination so the error or timeout has nothing related to the number of rows you have in your database.
Do you have a lot of hasOne or belongsTo associations in your `users` model? 

About the chart with the total number of users, I don't think the problem is related.
Was it working in the previous package version you were using?

**Comment by hermanschutte** [comment] 2016-12-05 10:01
Hi @arnaudbesnier,

Yes, each User has a UserWidget associated with it, which in turn have a Widget associated with it.

The chart was working before yes. With version 0.0.3.

**Comment by hermanschutte** [comment] 2016-12-12 14:20
@arnaudbesnier any update on this issue?

**Comment by arnaudbesnier** [comment] 2016-12-12 16:26
@hermanschutte, no update yet, I didn't took the time to look deeper into the issue.
I feel like it will be hard for me to reproduce the issue unless you accept to share with me the declaration of your `users` model (or at least the reduced part of your model that create the issue).

If you don't want to share it on Github, maybe you can send it to me by email or any other way you like. What do you think?

**Comment by hermanschutte** [comment] 2016-12-14 14:09
@arnaudbesnier sure, I will send you the declaration of our model via email.

**Comment by arnaudbesnier** [comment] 2017-01-27 12:45
Ok so it seems related to your `oauthIdentities` hasOne relationship. It's hard for me to believe that this association generates a timeout for the request. Can you show me a screenshot of the request timeout response in your browser console?

Thanks

**Comment by arnaudbesnier** [comment] 2017-02-14 07:41
Ok, so the issue was due to a missing foreign key between your users and oauth_identities tables. Once you added this, the users are being returned correctly.

**Closed by arnaudbesnier** 2017-02-14 07:41 UTC
Labels: bug
